### ISSUE TITLE
is this proto-type deprecated ?

### ISSUE THREAD

**Issue by hintsofttech** [dotnet/Microsoft.Maui.Graphics.Controls#120] opened 2022-08-12 13:26 UTC
no updates or progress for this project found for a long time.
is this proto-type deprecated ?

**Comment by progmars** [comment] 2022-08-20 10:00
Duplicate of #108

**Comment by jsuarezruiz** [comment] 2022-08-21 11:31
And for now, only can share the same answer than https://github.com/dotnet/Microsoft.Maui.Graphics.Controls/issues/108#issuecomment-1083109110

Thanks for the interest in the project!

**Closed by jsuarezruiz** 2022-08-21 11:31 UTC
